export interface ExerciseEntry {
  id: string;
  name: string;           // French
  emoji: string;
  category: "cardio" | "musculation" | "sport" | "fonctionnel" | "flexibilite";
  met: number;            // MET value
  activityType: number;   // Google Fit type
  kcalPer30min75kg: number; // pre-calculated: met * 75 * 0.5
  muscles?: string[];
  equipment?: string[];
}

export const EXERCISE_CATALOG: ExerciseEntry[] = [
  // ── Cardio ────────────────────────────────────────────────────────────────
  {
    id: "run-slow",
    name: "Course lente",
    emoji: "🏃",
    category: "cardio",
    met: 7,
    activityType: 1,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Quadriceps", "Mollets", "Fessiers"],
    equipment: [],
  },
  {
    id: "run-moderate",
    name: "Course modérée",
    emoji: "🏃",
    category: "cardio",
    met: 9,
    activityType: 1,
    kcalPer30min75kg: Math.round(9 * 75 * 0.5),
    muscles: ["Quadriceps", "Ischio-jambiers", "Mollets"],
    equipment: [],
  },
  {
    id: "run-fast",
    name: "Course rapide",
    emoji: "🏃",
    category: "cardio",
    met: 11.5,
    activityType: 1,
    kcalPer30min75kg: Math.round(11.5 * 75 * 0.5),
    muscles: ["Quadriceps", "Ischio-jambiers", "Fessiers", "Mollets"],
    equipment: [],
  },
  {
    id: "sprint",
    name: "Sprint",
    emoji: "⚡",
    category: "cardio",
    met: 14,
    activityType: 1,
    kcalPer30min75kg: Math.round(14 * 75 * 0.5),
    muscles: ["Quadriceps", "Ischio-jambiers", "Fessiers", "Mollets"],
    equipment: [],
  },
  {
    id: "bike-flat",
    name: "Vélo plat",
    emoji: "🚴",
    category: "cardio",
    met: 6,
    activityType: 7,
    kcalPer30min75kg: Math.round(6 * 75 * 0.5),
    muscles: ["Quadriceps", "Mollets", "Fessiers"],
    equipment: ["Vélo"],
  },
  {
    id: "bike-hill",
    name: "Vélo en côte",
    emoji: "🚵",
    category: "cardio",
    met: 10,
    activityType: 7,
    kcalPer30min75kg: Math.round(10 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Mollets"],
    equipment: ["Vélo"],
  },
  {
    id: "spinning",
    name: "Spinning / Vélo d'appartement",
    emoji: "🚴",
    category: "cardio",
    met: 8.5,
    activityType: 7,
    kcalPer30min75kg: Math.round(8.5 * 75 * 0.5),
    muscles: ["Quadriceps", "Ischio-jambiers", "Mollets"],
    equipment: ["Vélo stationnaire"],
  },
  {
    id: "swim-crawl",
    name: "Natation crawl",
    emoji: "🏊",
    category: "cardio",
    met: 8,
    activityType: 93,
    kcalPer30min75kg: Math.round(8 * 75 * 0.5),
    muscles: ["Épaules", "Dos", "Triceps", "Abdominaux"],
    equipment: ["Piscine"],
  },
  {
    id: "swim-backstroke",
    name: "Natation dos crawlé",
    emoji: "🏊",
    category: "cardio",
    met: 7,
    activityType: 93,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Dos", "Épaules", "Biceps"],
    equipment: ["Piscine"],
  },
  {
    id: "jump-rope",
    name: "Corde à sauter",
    emoji: "🪢",
    category: "cardio",
    met: 10,
    activityType: 9,
    kcalPer30min75kg: Math.round(10 * 75 * 0.5),
    muscles: ["Mollets", "Épaules", "Abdominaux"],
    equipment: ["Corde à sauter"],
  },
  {
    id: "rowing",
    name: "Rameur",
    emoji: "🚣",
    category: "cardio",
    met: 7,
    activityType: 37,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Dos", "Biceps", "Épaules", "Quadriceps"],
    equipment: ["Rameur"],
  },
  {
    id: "fast-walk",
    name: "Marche rapide",
    emoji: "🚶",
    category: "cardio",
    met: 4.5,
    activityType: 46,
    kcalPer30min75kg: Math.round(4.5 * 75 * 0.5),
    muscles: ["Quadriceps", "Mollets"],
    equipment: [],
  },
  {
    id: "elliptical",
    name: "Elliptique",
    emoji: "🏋️",
    category: "cardio",
    met: 6.5,
    activityType: 0,
    kcalPer30min75kg: Math.round(6.5 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Mollets", "Épaules"],
    equipment: ["Elliptique"],
  },
  {
    id: "step",
    name: "Step",
    emoji: "👟",
    category: "cardio",
    met: 7.5,
    activityType: 9,
    kcalPer30min75kg: Math.round(7.5 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Mollets"],
    equipment: ["Step"],
  },

  // ── Musculation ───────────────────────────────────────────────────────────
  {
    id: "squat",
    name: "Squat",
    emoji: "🏋️",
    category: "musculation",
    met: 6,
    activityType: 17,
    kcalPer30min75kg: Math.round(6 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers"],
    equipment: ["Barre", "Rack"],
  },
  {
    id: "bench-press",
    name: "Développé couché",
    emoji: "🏋️",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Pectoraux", "Triceps", "Épaules"],
    equipment: ["Barre", "Banc"],
  },
  {
    id: "deadlift",
    name: "Soulevé de terre",
    emoji: "🏋️",
    category: "musculation",
    met: 6,
    activityType: 17,
    kcalPer30min75kg: Math.round(6 * 75 * 0.5),
    muscles: ["Dos", "Fessiers", "Ischio-jambiers", "Trapèzes"],
    equipment: ["Barre"],
  },
  {
    id: "pull-ups",
    name: "Tractions",
    emoji: "💪",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Dos", "Biceps", "Épaules"],
    equipment: ["Barre de traction"],
  },
  {
    id: "dips",
    name: "Dips",
    emoji: "💪",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Triceps", "Pectoraux", "Épaules"],
    equipment: ["Barres parallèles"],
  },
  {
    id: "bicep-curl",
    name: "Curl biceps",
    emoji: "💪",
    category: "musculation",
    met: 4.5,
    activityType: 17,
    kcalPer30min75kg: Math.round(4.5 * 75 * 0.5),
    muscles: ["Biceps", "Avant-bras"],
    equipment: ["Haltères ou barre"],
  },
  {
    id: "overhead-press",
    name: "Presse militaire",
    emoji: "🏋️",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Épaules", "Triceps", "Trapèzes"],
    equipment: ["Barre ou haltères"],
  },
  {
    id: "leg-press",
    name: "Leg press",
    emoji: "🦵",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers"],
    equipment: ["Machine leg press"],
  },
  {
    id: "tricep-ext",
    name: "Extensions triceps",
    emoji: "💪",
    category: "musculation",
    met: 4,
    activityType: 17,
    kcalPer30min75kg: Math.round(4 * 75 * 0.5),
    muscles: ["Triceps"],
    equipment: ["Haltères ou câbles"],
  },
  {
    id: "barbell-row",
    name: "Rowing barre",
    emoji: "🏋️",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Dos", "Biceps", "Trapèzes"],
    equipment: ["Barre"],
  },
  {
    id: "lunges",
    name: "Fentes",
    emoji: "🦵",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers"],
    equipment: [],
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    emoji: "🍑",
    category: "musculation",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Fessiers", "Ischio-jambiers"],
    equipment: ["Banc", "Barre"],
  },
  {
    id: "plank",
    name: "Gainage",
    emoji: "🧱",
    category: "musculation",
    met: 4,
    activityType: 17,
    kcalPer30min75kg: Math.round(4 * 75 * 0.5),
    muscles: ["Abdominaux", "Dos", "Épaules"],
    equipment: [],
  },

  // ── Sport ─────────────────────────────────────────────────────────────────
  {
    id: "football",
    name: "Football",
    emoji: "⚽",
    category: "sport",
    met: 7,
    activityType: 45,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Quadriceps", "Mollets", "Fessiers"],
    equipment: ["Ballon"],
  },
  {
    id: "tennis",
    name: "Tennis",
    emoji: "🎾",
    category: "sport",
    met: 6.5,
    activityType: 54,
    kcalPer30min75kg: Math.round(6.5 * 75 * 0.5),
    muscles: ["Épaules", "Avant-bras", "Jambes"],
    equipment: ["Raquette", "Balles"],
  },
  {
    id: "basketball",
    name: "Basketball",
    emoji: "🏀",
    category: "sport",
    met: 7,
    activityType: 0,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Jambes", "Épaules"],
    equipment: ["Ballon"],
  },
  {
    id: "badminton",
    name: "Badminton",
    emoji: "🏸",
    category: "sport",
    met: 5.5,
    activityType: 0,
    kcalPer30min75kg: Math.round(5.5 * 75 * 0.5),
    muscles: ["Épaules", "Avant-bras", "Jambes"],
    equipment: ["Raquette", "Volant"],
  },
  {
    id: "volleyball",
    name: "Volleyball",
    emoji: "🏐",
    category: "sport",
    met: 5,
    activityType: 74,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Jambes", "Épaules", "Abdominaux"],
    equipment: ["Ballon"],
  },
  {
    id: "boxing",
    name: "Boxe",
    emoji: "🥊",
    category: "sport",
    met: 9,
    activityType: 104,
    kcalPer30min75kg: Math.round(9 * 75 * 0.5),
    muscles: ["Épaules", "Dos", "Abdominaux", "Jambes"],
    equipment: ["Gants", "Sac de frappe"],
  },
  {
    id: "martial-arts",
    name: "Arts martiaux / MMA",
    emoji: "🥋",
    category: "sport",
    met: 8,
    activityType: 0,
    kcalPer30min75kg: Math.round(8 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "skiing",
    name: "Ski",
    emoji: "⛷️",
    category: "sport",
    met: 7,
    activityType: 10,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Abdominaux"],
    equipment: ["Skis"],
  },

  // ── Fonctionnel ───────────────────────────────────────────────────────────
  {
    id: "hiit",
    name: "HIIT",
    emoji: "🔥",
    category: "fonctionnel",
    met: 9,
    activityType: 9,
    kcalPer30min75kg: Math.round(9 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "burpees",
    name: "Burpees",
    emoji: "💥",
    category: "fonctionnel",
    met: 8,
    activityType: 9,
    kcalPer30min75kg: Math.round(8 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "kettlebell",
    name: "Kettlebell",
    emoji: "🏋️",
    category: "fonctionnel",
    met: 7,
    activityType: 17,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Corps entier", "Fessiers", "Dos"],
    equipment: ["Kettlebell"],
  },
  {
    id: "crossfit",
    name: "CrossFit",
    emoji: "🏅",
    category: "fonctionnel",
    met: 9.5,
    activityType: 9,
    kcalPer30min75kg: Math.round(9.5 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: ["Variable"],
  },
  {
    id: "circuit-training",
    name: "Circuit training",
    emoji: "🔄",
    category: "fonctionnel",
    met: 8,
    activityType: 9,
    kcalPer30min75kg: Math.round(8 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "trx",
    name: "TRX / Sangles",
    emoji: "🔗",
    category: "fonctionnel",
    met: 6.5,
    activityType: 17,
    kcalPer30min75kg: Math.round(6.5 * 75 * 0.5),
    muscles: ["Corps entier", "Abdominaux", "Dos"],
    equipment: ["TRX"],
  },
  {
    id: "tabata",
    name: "Tabata",
    emoji: "⏱️",
    category: "fonctionnel",
    met: 9,
    activityType: 9,
    kcalPer30min75kg: Math.round(9 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },

  // ── Flexibilité ───────────────────────────────────────────────────────────
  {
    id: "yoga",
    name: "Yoga",
    emoji: "🧘",
    category: "flexibilite",
    met: 3,
    activityType: 82,
    kcalPer30min75kg: Math.round(3 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: ["Tapis"],
  },
  {
    id: "yoga-hot",
    name: "Yoga chaud (Bikram)",
    emoji: "🧘",
    category: "flexibilite",
    met: 4,
    activityType: 82,
    kcalPer30min75kg: Math.round(4 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: ["Tapis"],
  },
  {
    id: "pilates",
    name: "Pilates",
    emoji: "🤸",
    category: "flexibilite",
    met: 3.5,
    activityType: 82,
    kcalPer30min75kg: Math.round(3.5 * 75 * 0.5),
    muscles: ["Abdominaux", "Dos", "Fessiers"],
    equipment: ["Tapis"],
  },
  {
    id: "stretching",
    name: "Stretching",
    emoji: "🙆",
    category: "flexibilite",
    met: 2.5,
    activityType: 82,
    kcalPer30min75kg: Math.round(2.5 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "tai-chi",
    name: "Tai Chi",
    emoji: "☯️",
    category: "flexibilite",
    met: 3,
    activityType: 82,
    kcalPer30min75kg: Math.round(3 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "foam-roll",
    name: "Récupération / Foam roller",
    emoji: "🧸",
    category: "flexibilite",
    met: 2,
    activityType: 82,
    kcalPer30min75kg: Math.round(2 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: ["Foam roller"],
  },
  // ── Extra cardio ──────────────────────────────────────────────────────────
  {
    id: "hiit-cycling",
    name: "HIIT vélo",
    emoji: "🚴",
    category: "cardio",
    met: 10,
    activityType: 7,
    kcalPer30min75kg: Math.round(10 * 75 * 0.5),
    muscles: ["Quadriceps", "Ischio-jambiers", "Fessiers"],
    equipment: ["Vélo stationnaire"],
  },
  {
    id: "stair-climber",
    name: "Stepper / Escaliers",
    emoji: "🪜",
    category: "cardio",
    met: 8,
    activityType: 55,
    kcalPer30min75kg: Math.round(8 * 75 * 0.5),
    muscles: ["Fessiers", "Quadriceps", "Mollets"],
    equipment: [],
  },
  // ── Extra musculation ─────────────────────────────────────────────────────
  {
    id: "push-ups",
    name: "Pompes",
    emoji: "💪",
    category: "musculation",
    met: 4,
    activityType: 17,
    kcalPer30min75kg: Math.round(4 * 75 * 0.5),
    muscles: ["Pectoraux", "Triceps", "Épaules"],
    equipment: [],
  },
  {
    id: "ab-crunches",
    name: "Abdos / Crunchs",
    emoji: "🧱",
    category: "musculation",
    met: 4,
    activityType: 17,
    kcalPer30min75kg: Math.round(4 * 75 * 0.5),
    muscles: ["Abdominaux"],
    equipment: [],
  },
  {
    id: "calf-raises",
    name: "Mollets debout",
    emoji: "🦵",
    category: "musculation",
    met: 3.5,
    activityType: 17,
    kcalPer30min75kg: Math.round(3.5 * 75 * 0.5),
    muscles: ["Mollets"],
    equipment: [],
  },
  // ── Extra sport ───────────────────────────────────────────────────────────
  {
    id: "handball",
    name: "Handball",
    emoji: "🤾",
    category: "sport",
    met: 7,
    activityType: 0,
    kcalPer30min75kg: Math.round(7 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: ["Ballon"],
  },
  {
    id: "cycling-road",
    name: "Vélo de route",
    emoji: "🚵",
    category: "cardio",
    met: 9,
    activityType: 7,
    kcalPer30min75kg: Math.round(9 * 75 * 0.5),
    muscles: ["Quadriceps", "Fessiers", "Mollets"],
    equipment: ["Vélo de route"],
  },
  {
    id: "swimming-breaststroke",
    name: "Natation brasse",
    emoji: "🏊",
    category: "cardio",
    met: 7.5,
    activityType: 93,
    kcalPer30min75kg: Math.round(7.5 * 75 * 0.5),
    muscles: ["Pectoraux", "Dos", "Jambes"],
    equipment: ["Piscine"],
  },
  {
    id: "rugby",
    name: "Rugby",
    emoji: "🏉",
    category: "sport",
    met: 8.3,
    activityType: 109,
    kcalPer30min75kg: Math.round(8.3 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: ["Ballon"],
  },
  {
    id: "golf",
    name: "Golf",
    emoji: "⛳",
    category: "sport",
    met: 4.5,
    activityType: 0,
    kcalPer30min75kg: Math.round(4.5 * 75 * 0.5),
    muscles: ["Épaules", "Dos", "Core"],
    equipment: ["Clubs"],
  },
  {
    id: "dance",
    name: "Danse",
    emoji: "💃",
    category: "sport",
    met: 5,
    activityType: 83,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Jambes", "Core"],
    equipment: [],
  },
  {
    id: "zumba",
    name: "Zumba",
    emoji: "🕺",
    category: "fonctionnel",
    met: 6,
    activityType: 83,
    kcalPer30min75kg: Math.round(6 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
  {
    id: "bodyweight-training",
    name: "Entraînement poids du corps",
    emoji: "🤸",
    category: "fonctionnel",
    met: 5,
    activityType: 17,
    kcalPer30min75kg: Math.round(5 * 75 * 0.5),
    muscles: ["Corps entier"],
    equipment: [],
  },
];
